sources:
  - name: franceinfo_titres
    url: https://www.francetvinfo.fr/titres.rss
    topic: general
  - name: lemonde_une
    url: https://www.lemonde.fr/rss/une.xml
    topic: general
  - name: bfmtv_all
    url: https://www.bfmtv.com/rss/info/flux-rss/flux-toutes-les-actualites/
    topic: general
  - name : lactualite_general
    url : https://lactualite.com/feed/
    topic: general
